name: open_meteo_api
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.21.1
